export const GET_CONTACT_LIST = 'GET_CONTACT_LIST';
export const GET_CONTACT_LIST_FULFILLED = 'GET_CONTACT_LIST_FULFILLED';
export const GET_CONTACT_LIST_REJECTED = 'GET_CONTACT_LIST_REJECTED';

export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_FULFILLED = 'GET_CONTACT_FULFILLED';
export const GET_CONTACT_REJECTED = 'GET_CONTACT_REJECTED';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_CONTACT_FULFILLED = 'UPDATE_CONTACT_FULFILLED';
export const UPDATE_CONTACT_REJECTED = 'UPDATE_CONTACT_REJECTED';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_FULFILLED = 'DELETE_CONTACT_FULFILLED';
export const DELETE_CONTACT_REJECTED = 'DELETE_CONTACT_REJECTED';

export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_CONTACT_FULFILLED = 'ADD_CONTACT_FULFILLED';
export const ADD_CONTACT_REJECTED = 'ADD_CONTACT_REJECTED';
